# Generated by Django 3.0.3 on 2020-02-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymous',
            options={'verbose_name': 'Anonymous', 'verbose_name_plural': 'Anonymous'},
        ),
        migrations.AddField(
            model_name='anonymous',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='anonymous',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
